// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSyut8I6bajISU9Igj08vVIwvWhb0TTlM',
    appId: '1:897217641932:android:ba188c4e4b699546e97169',
    messagingSenderId: '897217641932',
    projectId: 'appproject-e8710',
    databaseURL:
        'https://appproject-e8710-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appproject-e8710.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIwC2zmLue8qJqSa1K7F76iYsP_ZsTdEU',
    appId: '1:897217641932:ios:826fe22e90fddf87e97169',
    messagingSenderId: '897217641932',
    projectId: 'appproject-e8710',
    databaseURL:
        'https://appproject-e8710-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'appproject-e8710.appspot.com',
    iosClientId:
        '897217641932-iede7nmvcjd0e6gt581uodpapf2ma939.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectA',
  );
}
